DROP TABLE IF EXISTS pokemon CASCADE;
DROP TABLE IF EXISTS color CASCADE;
DROP TABLE IF EXISTS habitat CASCADE;
DROP TABLE IF EXISTS shape CASCADE;
DROP TABLE IF EXISTS species CASCADE;

CREATE TABLE pokemon (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  poke_name TEXT NOT NULL,
  url_ TEXT NOT NULL
);

CREATE TABLE color (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  color TEXT NOT NULL,
  url_ TEXT NOT NULL
);

CREATE TABLE habitat (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url_ TEXT NOT NULL
);

CREATE TABLE shape (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url_ TEXT NOT NULL
);

CREATE TABLE species (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url_ TEXT NOT NULL
);