DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS color;

CREATE TABLE pokemon (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  poke_name TEXT NOT NULL,
  url_ TEXT NOT NULL
);


CREATE TABLE color (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  color TEXT NOT NULL,
  url_ TEXT NOT NULL
);